export { default as MainPage } from "./main";
export { default as ATCsPage } from "./atcs";
export { default as UserPage } from './user';
export { default as RolePage } from './role';
export { default as InteractionPage } from "./interaction";
export { default as PricesPage } from "./prices";
export { default as LoginPage } from "./login";
export { default as SignUpPage } from "./signup";
export { default as EditPage } from "./edit";
